<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Promises</p>
    

    <script>
        
    


    // const ticket = new Promise(function(resolve, reject){
    //     const isBoarded = true;
    //     if(isBoarded){
    //         resolve('You are not in the flight')
    //     }else{
    //         reject("You are not inthe flight")
    //     }
    // })

    // ticket.then((data) =>{
    //     console.log ('whoooo')

    // })
    // .catch((data) => {
    //     console.log ('you fligtht has been cancled')
    // })

    // .finally(() =>{
    //     console.log(" iwill alwaus executed ")
    // });

    // promise work in two step first creatand then use





    
function getCheese() {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            const cheese = "🧀";
            resolve(cheese);
        }, 2000);
    });
}

function makeDough(cheese) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            const dough = cheese + "🫓";
             resolve(dough);
            reject("Bad cheese");
        }, 2000);
    });
}

function bakePizza(dough) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            const pizza = dough + "🍕";
            resolve(pizza);
        }, 2000);
    });
}

async function orderPizza() {
     try {
        const cheese = await getCheese();
        console.log("here is the cheese", cheese);

        const dough = await makeDough(cheese);
        console.log("here is the dough", dough);

        const pizza = await bakePizza(dough);
        console.log("here is the pizza", pizza);
     } catch (err) {
        console.log("error occured", err);
     }
     console.log("Process ended");
 }

orderPizza();

// getCheese()
//     .then((cheese) => {
//         console.log("here is the cheese", cheese);
//         return makeDough(cheese);
//     })
//     .then((dough) => {
//         console.log("here is the dough", dough);
//         return bakePizza(dough);
//     })
//     .then((pizza) => {
//         console.log("here is the pizza", pizza);
//     })
//     .catch((data) => {
//         console.log("error occured", data);
//     })
//     .finally(() => {
//         console.log("Process ended");
//     });











   
    
    </script>


</body>
</html>